apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: mod488/newsifier-user
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-mysql-secret
                key: password
          - name: DB_USER
            value: 'root'      
          - name: DB_HOST
            value: 'user-mysql-srv'
          - name: DB_DRIVER
            value: 'mysql'
          - name: DB_NAME
            value: 'newsifier_users'
          - name: TEST_DB_NAME
            value: 'newsifier_users_test'               
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
  - name: user
    protocol: TCP
    port: 3000
    targetPort: 3000
   